raiden-network/spec

- smart_contracts.rst
- removes open questions and opened issues for them instead
- small fixes
> SC specs - remove open questions

- pathfinding_service.rst
* Switch from JSON-RPC to REST
* Remove solved questions
> Update pathfinding_servce specs

- messaging.rst
- pathfinding_service.rst
- smart_contracts.rst
- terminology.rst
> Replace hashlock with secrethash

- pathfinding_service.rst
@err508 I started the updates here. Please add your description here.
> Add infos about topology updates

- messaging.rst
- pathfinding_service.rst
- smart_contracts.rst
- terminology.rst
- transport.rst
> Update balance proof in messaging.rst

- smart_contracts.rst
Related to raiden-network/raiden-contracts#137
> Update spec for updated SecretRevealed event

- messaging.rst
- use message names from the current protocol, to be consistent
- fix message flow
> Fix Secret, RevealSecret messages

- smart_contracts.rst
Fixes https://github.com/raiden-network/spec/issues/97
> Update smart contract specs - channel identifier, batch registration

- smart_contracts.rst
Fixes https://github.com/raiden-network/spec/issues/86
Protocol value constraints and settlement algorithm (already implemented or in plan) were gathered and discussed here: https://github.com/raiden-network/raiden-contracts/issues/188
> Add protocol values constraints and settlement algorithm requirements

- messaging.rst
> Add pending transfer limit to the spec

- transport.rst
> Update transport spec according to current implementation/protocol

- terminology.rst
Fixes https://github.com/raiden-network/spec/issues/111
> Improve nonce explanation.

- smart_contracts.rst
Fixes https://github.com/raiden-network/spec/issues/100
- updated security and privacy requirements
- updated requirements for channel operations
> Update smart contract requirements

- smart_contracts.rst
Fixes https://github.com/raiden-network/spec/issues/110
> Improve protocol value constraints & settlement analysis

- smart_contracts.rst
fixes https://github.com/raiden-network/spec/issues/67
Spec updated after https://github.com/raiden-network/raiden-contracts/pull/252, and discussions https://github.com/raiden-network/raiden-contracts/issues/241
- added new format and order of fields for the signed messages
- added message type identifiers for each signed message
- added missing balance update proof signed message
> Update signed message format for smart contracts

- smart_contracts.rst
fixes https://github.com/raiden-network/spec/issues/118
- add links to `raiden` & `raiden-contracts` code where constraints are implemented
- add missing `(5.1 R) L1 <= AB1, L1 <= TAD, L1 >= 0`
> Add code reference for protocol constraints

- smart_contracts.rst
fixes https://github.com/raiden-network/spec/issues/125
> Add EndpointRegistry spec

- messaging.rst
> Describe how many Merkle trees are involved

- pathfinding_service.rst
Changes in response to https://github.com/raiden-network/raiden-pathfinding-service/issues/83#issuecomment-447008346.
@LefterisJP @palango @Dominik1999: Are you all ok with this? If this gets merged, I'll update the PFS code accordingly.
> Lefteris PFS-API feedback

- messaging.rst
- terminology.rst
This is a part of https://github.com/raiden-network/spec/issues/162
> Unlock message in the terminology

- terminology.rst
for people interested in how the capacity in computed.
> A link from capacity in terminology to equation

- smart_contracts.rst
in the return values of ``getChannelParticipantInfo()``.
> Explain what ``deposit`` is

- messaging.rst
- terminology.rst
> Document validity conditions for Secret Request

- contracts/LICENSE
This is a leftover from https://github.com/raiden-network/spec/pull/202
> Copy LICENSE from raiden-contracts repository

- monitoring_service.rst
- service_contracts.rst
- transport.rst
Closes https://github.com/raiden-network/raiden-contracts/issues/480
> Rename RaidenServiceBundle to ServiceRegistry

- messaging.rst
- pathfinding_service.rst
Draft of the PFS update message.
> Add Update message for pathfinding service

- pathfinding_service.rst
- service_contracts.rst
> Add some more details to the PFS payment info

- pathfinding_service.rst
- service_contracts.rst
TODO:
Postponed to later PRs:
- add error codes and add them to the examples
> IOU endpoint for PFS

- pathfinding_service.rst
Updates the `PFSUpdate` message spec as per our discussion.
> Update PFSUpdate message spec

- monitoring_service.rst
- pathfinding_service.rst
...which was quite outdated in some parts.
* Fix totally wrong/outdated description of the info endpoint
* Bring name of `iou` parameter in line with current implementation
* Update routing preference description
> Update the PFS documentation

- service_contracts.rst
Relates to https://github.com/raiden-network/raiden-services/issues/267
and https://github.com/raiden-network/raiden-contracts/issues/849.
> Add new IOU fields to OneToN description

- pathfinding_service.rst
Closes https://github.com/raiden-network/raiden-services/issues/336
> Add spec for routing feedback.

- monitoring_service.rst
according to https://github.com/raiden-network/raiden-contracts/issues/1117
> Update reward proof

- pathfinding_service.rst
Adds a readable description of routing feedback.
> Pfs update

- smart_contracts.rst
This follows the change in the implementation
https://github.com/raiden-network/raiden-contracts/pull/655
This commit is a part of updating the specification:
> Add new arguments of createERC20TokenNetwork()

- mediation_fees.rst
This reflects the changes done in
https://github.com/raiden-network/raiden/pull/4901
> Update imbalance fee usage

- index.rst
> Define a goal for the specs

- messaging.rst
See https://github.com/raiden-network/raiden/pull/4935 and
https://github.com/raiden-network/raiden/pull/4973 for the changes in
the code. This assumes that the latter will get merged.
> Update `WithdrawExpired` after signature change

- pathfinding_service.rst
Closes https://github.com/raiden-network/spec/issues/287 and closes https://github.com/raiden-network/spec/issues/288
> Update service messages description

- index.rst
- introduction.rst
- readthedocs.yaml
- Make introduction a chapter, so it is visible in the table of contents
- add requirements file to `readthedocs.yaml`, as some builds failed due to non-installed requirements.
> Two small changes

- smart_contracts.rst
chapter because it was just one sentence.  This tries to close #296.
> Write Overview on Raiden Smart Contracts

- service_contracts.rst
and explain how to determine the set of currently registered
service providers.
> Document ServiceRegistry.ever_made_deposits()

- service_contracts.rst
This PR documents the deprecation of ServiceRegistry.
> Document Deprecation of ServiceRegistry

- .circleci/config.yml
- transport.rst
- Fixes the docs build error
- Adds a simple CI config, to stop people from destroying the build in the future
> Fix Sphinx build and add basic CircleCI config

- terminology.rst
- transport.rst
Add terminology entries for the service messages.
> Add term entries for service messages

- pathfinding_service.rst
> Add example PFS response

- smart_contracts.rst
> Replace emphasis with headings

- transport.rst
> Rename summary to overview in transport spec

- monitoring_service.rst
- pathfinding_service.rst
Part of https://github.com/raiden-network/spec/issues/252
> Improvements to services chapters

- contracts/lib/ECVerify.sol
- contracts/raiden/SecretRegistry.sol
- contracts/raiden/Token.sol
- contracts/raiden/TokenNetwork.sol
- contracts/raiden/TokenNetworkRegistry.sol
- contracts/raiden/Utils.sol
- contracts/services/MonitoringService.sol
- contracts/services/OneToN.sol
- contracts/services/ServiceRegistry.sol
- contracts/services/UserDeposit.sol
- contracts/test/CustomToken.sol
- contracts/test/HumanStandardToken.sol
- contracts/test/MonitoringServiceInternalsTest.sol
- contracts/test/OneToNInternalsTest.sol
- contracts/test/SignatureVerifyTest.sol
- contracts/test/StandardToken.sol
- contracts/test/TokenNetworkInternalsTest.sol
- contracts/test/UDCTransfer.sol
This is done using `make update_contracts` and committing the resulting
changes.
Closes https://github.com/raiden-network/spec/issues/255.
> Update contract sources for autodoc

- pathfinding_service.rst
As requested in https://github.com/raiden-network/raiden/issues/5897.
> Explain fee update timing

- transport.rst
As taken from https://github.com/raiden-network/raiden/issues/6503#issuecomment-704310156
Part of https://github.com/raiden-network/team/issues/882
> Add capabilites docs to transport page

- smart_contracts.rst
The settlement was only explained in the diagram, which does not
convey information like timing differences, links to functions,
purpose, etc. Since the settlement is an essential part of Raiden,
having some explanatory text makes a lot of sense.
The coop settle is not enabled right now, but I consider it to be part
of the spec, nevertheless.
> Add settlement explanation

- pathfinding_service.rst
- Add metadata endpoint and additional metadata from path response
- Add `online_addresses` endpoint
- Update `info` endpoint to `v2`
> Add new PFS endpoints and update outdated PFS endpoints
