raiden-network/spec

pathfinding_service.rst

The PFS should be able to handle multiple token networks.
In order to know which token network should be updated or for which token network paths are requested the PFS needs the know the target token network address.
Not sure about the payment stuff: It would make sense to pay more for a bigger token network, but that may complicate the payment process.

Add token network address to all api endpoints

---

terminology.rst

Fix #60.
@loredanacirstea is that where in the spec you wanted it specified? In all other places it's shown as `bytes32` in the signature of the functions so should be clear.

Specify secret size

---

messaging.rst
smart_contracts.rst
terminology.rst

fixes https://github.com/raiden-network/spec/issues/70 (TokenNetwork `ChannelSettled` event - add the transferred amounts as arguments)
fixes https://github.com/raiden-network/spec/issues/71 (add cooperative settle signature format)
fixes https://github.com/raiden-network/spec/issues/75 (Update smart contract specs after `channel_identifier` changes from limiting the number of channels between two participants to one)
fixes https://github.com/raiden-network/spec/issues/26 (adds withdraw specs for smart contracts and messages)

Update smart contracts specs after withdraw, cooperative settle, channel limit

---

smart_contracts.rst

After merging https://github.com/raiden-network/raiden-contracts/pull/131, the `settleChannel` participant data ordering counts. This PR adds a note on how the function must be called now.

Add settleChannel participant order note

---

messaging.rst

The direct transfer must only change the transferred amount, the merkle
tree must stay intact, therefore the locked_amount and the locks_root
must be not change in respect to the previous message. Additionally the
message must be for a valid channel, meaning it must be tied to a
specific channel, from a specific token network, for a specific
blockchain, and the channel must be open.

Missing constraints for the direct transfer

---

messaging.rst
smart_contracts.rst
terminology.rst

The mediated transfer must only change the the merkle tree, the
transferred amount must stay intact, therefore the locked_amount and the
locks_root must change to include the new lock in respect to the
previous message. Additionally the message must be for a valid channel,
meaning it must be tied to a specific channel, from a specific token
network, for a specific blockchain, and the channel must be open.

Missing constraints for mediated transfers

---

smart_contracts.rst

Fixes https://github.com/raiden-network/spec/issues/101
- Fix setTotalWithdraw specs after removing partner argument - `partner` argument was removed from `setTotalWithdraw` in https://github.com/raiden-network/raiden-contracts/pull/251
- Fix cooperative settle & withdraw proof specs

Fix sc proof specs

---

pathfinding_service.rst

An example of a PUT /balance call on the pathfinding service didn't have some JSON fields.
This commit adds fields seen in a unit test (see https://github.com/raiden-network/spec/issues/130#issuecomment-439424438 )
Fixes #130.

Add fields in the pahtfinding service API call

---

smart_contracts.rst

This pull-request contains three tiny changes
* English clarification: participant payment pattern --> participant's payment pattern
* uniform notation for byte concatenation: `+` or `||`.
* explain how `message_length` is encoded.

Nitpick in signature format

---

smart_contracts.rst

This pull-request decomposes "Project Specification" section.  The section had a tiny bit of project specification and lots of smart contract descriptions.  So
* I moved the tiny bit of project specification to the "Project Requirments" section
* I renamed the section into "Smart Contract Decomposition".

Structure sections

---

smart_contracts.rst

Protocol Overview because the section only talked about the lifecycle of a single channel.

Rename Protocol Overview into TokenNetwork Channel

---

smart_contracts.rst

Both "balance proof update"s and "balance update proof"s appeared in the specification.  I think it's a balance proof update because it's about updating the balance proof.
Also added a cross-reference.

Balance Proof Update not Balance Update Proof

---

smart_contracts.rst

This commit moves the descriptions of `transferred_amount`,
`locked_amount` and `locksroot` under the `balance_hash` description
(as a nested list).
These three fields are here only to explain `balance_hash`.

Move balance hash elements under balance hash

---

smart_contracts.rst

because S1 (the amount that should be received) should not contain L1 (the amount to be held in the contract).
See https://github.com/raiden-network/spec/issues/145#issuecomment-442962717

S1 should exclude L1

---

smart_contracts.rst
terminology.rst

This PR is about https://github.com/raiden-network/spec/issues/144.
As continuation of https://github.com/raiden-network/spec/pull/131, I'm removing the word "message" from names of things for onchain calls.

Remove the word 'message' from onchain proofs

---

smart_contracts.rst

This one line commit fixes the bullet list format. A bullet list
requires one empty line above.

Fix the bullet point format

---

smart_contracts.rst

"equation1, equation2" is a bit ambiguous because it might mean
"equation1 and equation2" or "equation1 if equation2".  This commit
tries to disambiguate the situation a bit, by saying "if" explicitly.

Add "if" on timing conditions

---

smart_contracts.rst

`L1 <= AB1` is a weird condition because AB1 is 'something - L1'.
So the condition was `L1 <= something - L1`, and I had a suspicion that
`L1` is counted twice here.
After some investigation, I'm sure this condition is not needed.

Remove L1 <= AB1

---

smart_contracts.rst

Before this commit, there were two conditions that were named (10 R) and (10).  Usually the same number is never used more than once.  So I renamed (10 R) into (11 R).

Rename one of the two (10), into (11)

---

smart_contracts.rst

because it is also a crucial constraint that has to be guaranteed somewhere.  I chose (12) because (11) is booked in https://github.com/raiden-network/spec/pull/152.

Give a name to constraint ``D1 + D2 < 2^256``

---

messaging.rst

Before this commit, the bullet list was typeset as one big paragraph.

Add a required empty line before a bullet list

---

messaging.rst
terminology.rst

1. clarify additional_hash is in addition to what
2. explain that additional_hash is currently the hash of the offchain message
3. add a link from messaging.rst into additional_hash in the terminology.
This commit rescues some results from the discussion here https://github.com/raiden-network/spec/pull/136#discussion_r237393201

Update description of additional_hash

---

smart_contracts.rst

because people might read the specification and believe that these
commented-out functions are available.

Warn that some functions are not available

---

messaging.rst

In a mediated transfer from Alice--Bob--Charlie (with N=1 hop), three
Secret Reveal messages should be involved.
1. Alice to Charlie
2. Charlie to Bob
3. Bob to Alice
Another way to look at this: there should be one more Secret Reveal messages than Secret
(or Unlock) messages.

One more Secret Reveal is required

---

messaging.rst

Secret Request contains more fields than were described.  I also added a link to the corresponding part of the implementation.

Describe all fields of SecretRequest messages

---

smart_contracts.rst

The specification of TokenNetworkRegistry contract lacked an
introductory short summary.

Add a short description to TokenNetworkRegistry

---

messaging.rst

This commit
- adds some fields that were missing before
- adds a link to the corresponding part of code
- adds an explanation what kind of signature is included
to the specification of the Unlock message.

Describe all fields of Unlock message

---

messaging.rst
terminology.rst

There were some links to :term:`Locked Transfer` but `terminology.rst` did not have that entry.
This is a part of https://github.com/raiden-network/spec/issues/162.

Add Locked Transfer in the terminology

---

messaging.rst
terminology.rst

This commit adds Secret Reveal messages in the terminology, and adds a link to the new entry.
This work is a part of https://github.com/raiden-network/spec/issues/162

Secret Reveal messages in the terminology

---

smart_contracts.rst

Document the fact that registerSecret() fails if

---

smart_contracts.rst

Like all other variables, ``participant1_amount`` and ``participant2_amount`` need explanations.

Describe participant{1,2}_amount

---

smart_contracts.rst

There was a section titled "Update non-closing participant balance proof" which was not clear. This could be about the balance proof signed by the non-closing participant or the balance proof useful for the non-closing participant. Actually, this section is about the balance proof useful for the non-closing participant.

Rephrase "non-closing participant balance proof"

---

smart_contracts.rst
terminology.rst

The meaning of ``settle_block_number`` is worth explaining because the number means different things according to different states of the channel.

Explain settle_block_number from getChannelInfo()

---

messaging.rst
terminology.rst

The message was called Secret Reveal in the specification but in the
implementation it was called Reveal Secret.  Some fields were missing
from the spec.

Update the Reveal Secret spec

---

smart_contracts.rst

The caller of setTotalDeposit() has to approve

---

messaging.rst

Add a missing link to terminology

---

terminology.rst

As the name suggests, refund transfer is sending a transfer and not a
payment backwards.

Change from Payment to Transfer in the Refund terminology

---

Makefile

They are just a copy/paste leftover from the time when `spec/Makefile`
has been created based on `raiden/docs/Makefile`. Nobody noticed because
make didn’t stop execution. With the missing env var, the command
started with a minus, causing make to ignore errors.

Remove broken lines from `Makefile`

---

.gitignore
Makefile
contracts/EndpointRegistry.sol
contracts/SecretRegistry.sol
contracts/Token.sol
contracts/TokenNetwork.sol
contracts/TokenNetworkRegistry.sol
contracts/Utils.sol
contracts/lib/ECVerify.sol
contracts/services/MonitoringService.sol
contracts/services/RaidenServiceBundle.sol
contracts/services/UserDeposit.sol
contracts/test/CustomToken.sol
contracts/test/HumanStandardToken.sol
contracts/test/SignatureVerifyTest.sol
contracts/test/StandardToken.sol
contracts/test/TokenNetworkInternalsTest.sol
contracts/test/UDCTransfer.sol

It tried to avoid this but all alternatives were worse:
* make targets are not executed by readthedocs
* adding download code to conf.py would be surprising
* adding raiden-contracts to requirements.txt and getting the contracts
path from there worked fine locally, but readthedocs fails on
raiden-contracts' depencencies
* adding a custom readthedocs builder would be an overly complicated
solution to this problem
So unless somebody has a different solution it's this or no autodoc.

Add a copy of the contracts to repo for autodoc

---

service_contracts.rst

This is https://github.com/raiden-network/raiden-services/issues/38 with
only few changes. Spefic functions will be documented as the
implemenation makes progress.

Add OneToN spec

---

proofs/README.md
proofs/Settlement.thy

This is how I checked claims in the spec about the settlement algorithms.

Add Isabelle proof script on the settlement algo

---

messaging.rst
smart_contracts.rst
terminology.rst

following the recent change to the contracts
https://github.com/raiden-network/raiden-contracts/pull/1062

Replace Merkle trees with lists

---

monitoring_service.rst

We recently added the contract address and message type and rearranged
the fields. This needs to be reflected in the spec.

Update reward proof signature definition

---

smart_contracts.rst

This follows the implementation change made in
https://github.com/raiden-network/raiden-contracts/pull/1124
Now that anybody can call closeChannel() on behalf of the closing
party, the call now takes a signature of the closing party.

Document the new argument of closeChannel()

---

terminology.rst

So `make html` does not emit a warning.
This closes #259.

Add Balance Proof Update to terminology.rst

---

service_contracts.rst

This PR documents the interface of ServiceRegistry add adds a few sentences about the registration requirements on using MonitoringService and OneToN contracts.

Specify ServiceRegistry

---

smart_contracts.rst

Since Raiden client no longer supports UDP transport and
EndpointRegistry was removed.
https://github.com/raiden-network/raiden-contracts/pull/1013
This commit reflects that change in the spec.

Remove EndpointRegistry

---

smart_contracts.rst

This follows a change in the implementation
https://github.com/raiden-network/raiden-contracts/pull/1118/files
Two events got new arguments.
This commit is a part of solving https://github.com/raiden-network/spec/issues/253

Add new attributes in events

---

smart_contracts.rst

The implementation re-enabled setTotalWithdraw in
https://github.com/raiden-network/raiden-contracts/pull/711
This commit reflects the change in the spec.
This commit is a part of updating the spec:

setTotalWithdraw function is available now

---

smart_contracts.rst

from participant and partner into receiver and sender.
This change reflects the change made in the implementation
https://github.com/raiden-network/raiden-contracts/pull/988/files
This commit is a part of updating the spec

Rename unlock participants

---

smart_contracts.rst

This follows the implementation change made in
https://github.com/raiden-network/raiden-contracts/pull/1126
This commit is a part of updating the spec

Add locksroots in ChannelSettled event

---

smart_contracts.rst

The implementation changed the hash function
for the hashtimelocks
https://github.com/raiden-network/raiden-contracts/pull/979
This commit reflects that in the spec.
This commit is a part of updating the spec:

Hashlocks are on SHA256 now

---

smart_contracts.rst

I wanted to add a new event about the deprecation switch, but
the deprecation was never explained in the spec.
This commit is a part of updating the spec according to the implementation

Add description of the deprecation switch

---

smart_contracts.rst

This follows the implementation change in
https://github.com/raiden-network/raiden-contracts/pull/1150
Since Balance Proof Update message is used both for closeChnanel()
and updateNonClosingBalanceProof() call, the signature must be
differentiated using different message IDs.

Reflect Message ID differentiation for closing and updating

---

smart_contracts.rst

This commit adds the new argument `expiration_block` to
`setTotalWithdraw()` function.
The change follows the implementation
https://github.com/raiden-network/raiden-contracts/pull/1103
This commit is a part of updating the spec

Add expiration_block to setTotalWithdraw() args

---

smart_contracts.rst

This PR adds `max_token_network` attribute that's added in https://github.com/raiden-network/raiden-contracts/pull/652
It also explains other attributes.

Explain more attributes in TokenNetworkRegistry

---

smart_contracts.rst

This is a part of updating the spec
I had to add ``channel_participant_deposit_limit`` and
``token_network_deposit_limit``.  And then I noticed
that the attributes were never described.
I added new attributes and explained attributes.

Explain more attributes of TokenNetwork

---

index.rst
mediated_transfer.rst
messaging.rst
terminology.rst

The message format tables are still not up-to-date. There will be a follow-up for that.
Some changes to the messaging specification:
- add an Overview section (as is planned for all chapters of the spec)
- add some missing message and data structure descriptions
- structure the text better
- elaborate more on the structure of the balance proof
- move the transfer specification into an own chapter

Update messages specification for Alderaan

---

messaging.rst

In the last pr (#279), the specification of the `metadata` field of the `LockedTransfer` message was still missing.

Addendum to message spec

---

mediation_fees.rst

I took the relevant parts of the mediation fee ADR
https://github.com/raiden-network/raiden-services/blob/master/adr/003-mediation-fees.md and adapted it a bit to fit into the existing mediation fee page.
For the reasoning why we do it this way I just link to the ADR.
We're still missing the specification of the message format. I've added
that to https://github.com/raiden-network/raiden/issues/4696.
Closes https://github.com/raiden-network/spec/issues/251

Add imbalance fee explanation to fee page

---

messaging.rst

ReST needs a blank line before a bullet list.

Fix formatting of list

---

readthedocs.yaml

Using a config file is the recommended way to configure readthedocs. So
far we only used the web config UI.
Using this config file, I turned of all additional output formats fix
https://github.com/raiden-network/spec/issues/248. HTML & JSON are still
built.
I don't see a way to test this without merging, so it's untested.

Add config file and disable output formats

---

monitoring_service.rst

These
* throw errors when the link is broken
* link to local versions when building locally
* work inside PDFs

Use `ref`s for internal linking

---

mediation_fees.rst
messaging.rst
mobile_wallet.rst
monitoring_service.rst
pathfinding_service.rst
service_contracts.rst
smart_contracts.rst
terminology.rst
transport.rst

Do not repeat the words "Raiden" or "Specification" in chapter titles.
Related issue: #252

Consistent chapter titles / consistent table of contents

---

messaging.rst
monitoring_service.rst

- This chooses neutral language over first person speech, where applicable.
- This PR also tries to make some sentences easier to parse for humans.

Neutralize language

---

smart_contracts.rst

because otherwise Monitoring Services can gain
rewards again and again using the same reward proof.

Same balance proof update should not be repeated

---

smart_contracts.rst

Before this commit the spec said that only participants can close
a channel. But now anybody with right signatures can close a channel.
This change was introduced a while ago in the implementation to
improve the user experience on browser-based light clients.
However the spec has not caught up.
This fixes #273.

Anybody can close a channel with right sigs

---

service_contracts.rst

in the overview section of Service Contracts chapter.  This closes https://github.com/raiden-network/spec/issues/295.

Describe UserDeposit and ServiceRegistry

---

service_contracts.rst

Monitoring Services.
Because if all Monitoring Services can start at the same block,
there will be a race.
This trick was added in
https://github.com/raiden-network/raiden-contracts/pull/909
but I didn't find it mentioned in the spec.

Mention different monitoring period for different

---

service_contracts.rst

SecretRegistry detects when the deadline calculation overflows
and the deadline would be set in the past.
The check was added in
https://github.com/raiden-network/raiden-contracts/pull/1205
This commit describes this behavior in the spec.

SecretRegistry checks deadline overflows

---

monitoring_service.rst

These new fields were introduced in
https://github.com/raiden-network/raiden-contracts/pull/1238
to remove ambiguity.
This is a part of https://github.com/raiden-network/spec/issues/254.

Document new fields in the Reward Proof

---

service_contracts.rst

MonitoringService.monitor() fails for unregistered

---

mediation_fees.rst
pathfinding_service.rst

The formula is already used in the Raiden client. This supplies the
reasoning why the values are chosen as they are.

Explain calculation of default IP function

---

conf.py
mediation_fees.rst
requirements.txt

In https://github.com/raiden-network/raiden/pull/5089/files we changed
the mediation fee calculation to increase the accuracy and allow capping
the mediation fees in a sensible way. This commit brings the description
in line with the code, again.
Closes https://github.com/raiden-network/raiden-services/issues/410

Describe approximation-free mediation fees

---

conf.py
requirements.txt
smart_contracts.rst

We didn't add one when we added withdraw to the protocol. I added support for mermaid diagrams to do this easily.
See https://raiden-network-specification--340.org.readthedocs.build/en/340/smart_contracts.html#withdraw for the preview.

Add withdraw diagram 

---

smart_contracts.rst

- added the `TokenNetwork.openChannelWithDeposit` to the contracts
- renamed a mention of the deprecation executor for the TokenNetwork contract

Update TokenNetwork contract
